name: gradle_build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4.7.0
        with:
          java-version: 1.8
          distribution: 'Zulu' 
          
      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle build
        run: ./gradlew --build-cache build

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: build/libs
